### ISSUE TITLE
[BUG] ModuleNotFoundError: No module named 'webchanges._vendored'

### ISSUE THREAD

**Issue by verlanmar** [mborsetti/webchanges#14]
**Describe the bug**

webchanges does not launch

**To Reproduce**

simply run webchanges

**Screen scrape/screenshots**

![Screenshot 2021-08-02](https://user-images.githubusercontent.com/38294552/127892566-3a96ca23-8ffd-4cde-82e8-63ceb560cfe0.png)

**Version info**
 - webchanges 3.8
 - Python 3.9.6
 - System macOS 11.5.1

Also tried running webchanges in Docker (Ubuntu 21.04) with exactly the same error.

**Additional context**

Below is the error message from the terminal:

> webchanges --edit
Traceback (most recent call last):
  File "/usr/local/bin/webchanges", line 5, in <module>
    from webchanges.cli import main
  File "/usr/local/lib/python3.9/site-packages/webchanges/cli.py", line 19, in <module>
    from .command import UrlwatchCommand
  File "/usr/local/lib/python3.9/site-packages/webchanges/command.py", line 20, in <module>
    from .main import Urlwatch
  File "/usr/local/lib/python3.9/site-packages/webchanges/main.py", line 16, in <module>
    from ._vendored.packaging_version import parse as parse_version
ModuleNotFoundError: No module named 'webchanges._vendored'

**Comment by mborsetti** [comment]
Thanks for the report; fixed with v3.8.1, already published.

Apologies for the issue; new installations are tested *exactly* to avoid this type of issue (see tox.ini), but I was unknowingly a victim of a [tox bug](https://github.com/tox-dev/tox/issues/1485) so the test never run and the release went through even though it shouldn't have.
