### ISSUE TITLE
[BUG] A possible error in the docs

### ISSUE THREAD

**Issue by drws** [mborsetti/webchanges#44]
**Describe the bug**
[Here](https://webchanges.readthedocs.io/en/stable/examples.html?highlight=job_defaults#setting-default-headers) in the docs it says that

```
job_defaults:
  all:
    headers:
```

is the right structure to set HTTP headers globally, but [here](https://webchanges.readthedocs.io/en/stable/configuration.html?highlight=job_defaults#job-defaults) it says otherwise:

```
job_defaults:
  url:
    headers:
```

Which is the correct one?

**Comment by mborsetti** [comment]
Thanks for reporting this!  

It will get fixed in the next release.

For now you can refer to the the information [here]( https://webchanges.readthedocs.io/en/stable/configuration.html#:~:text=The%20possible%20sub,can%20be%20set) explaining the difference between `url` and `all` (which, in the case of `headers`, would apply the default to both `url` and `browser` as they are the only job types consuming `headers`).

**Comment by drws** [comment]
Thanks for clearing that up. I've just found another inconsistency - between [1](https://webchanges.readthedocs.io/en/stable/reports.html#optional-sub-directives) and [2](https://webchanges.readthedocs.io/en/stable/configuration.html?highlight=minimal#reporters). `show_details` and `show_footer` vs. `details` and `footer`.

**Comment by mborsetti** [comment]
Thank you for your feedback; very much appreciated!

**Comment by mborsetti** [comment]
Release 3.11 is out with your suggested fixes.  Thank you very much for taking the time to report this!
