### ISSUE TITLE
Incorrect numbering of jobs

### ISSUE THREAD

**Issue by Markus00000** [mborsetti/webchanges#9]
Job list:

    ---
    #name: Example homepage
    #url: https://example.org/
    ---
    # Some comment
    ---
    name: Example homepage
    url: https://example.org/
    ---

List of jobs:

    $ webchanges --list
    3: Example homepage (https://example.org/)

I expected the job to get number 1. Having a couple of uncommented jobs can make job lists quite confusing due to skipped numbers.

Tested with webchanges 3.5.1.

**Comment by mborsetti** [comment]
Yeah, technically according to the [specs](https://yaml.org/spec/1.1/) "YAML uses three dashes (“---”) to separate documents within a stream", or, in this case, jobs within a job list.  And agree with you that because of this the numbering ends up being weird, so will be filtering out empty jobs (“documents” in YAML-speak) in a future release before assigning them a number.

Thanks for your contribution!

**Comment by Markus00000** [comment]
Thanks in advance!

Also, if the job list is run there is whitespace in the output for each empty job or comment:

    $ webchanges
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    
    ===========================================================================
    01. NEW: Example homepage
    ===========================================================================
    
    ---------------------------------------------------------------------------
    NEW: Example homepage (https://example.org/)
    ---------------------------------------------------------------------------
    
    
    
    --

**Comment by mborsetti** [comment]
3.6.0 has been just released and it includes both your enhancement and a fix for the extra lines bug (plus a few more goodies).

Appreciate it!
